#---------------------------#
#         Database          #
#---------------------------#
[Database]
# Environment variable: `CL_DATABASE_URL`
# - URL is the PostgreSQL URI to connect to your database. Chainlink nodes require Postgres versions >= 11. See
# - [Running a Chainlink Node](https://docs.chain.link/docs/running-a-chainlink-node/#set-the-remote-database_url-config) for an example.
# - Example: URL = "postgresql://user:pass@localhost:5432/dbname?sslmode=disable" # Example
URL = ""

# Environment variable: `CL_DATABASE_BACKUP_URL`
# - BackupURL is where the automatic database backup will pull from, rather than the main DATABASE_URL.
# - It is recommended to set this value to a read replica if you have one to avoid excessive load on the main database.
# - Example: BackupURL = "postgresql://user:pass@read-replica.example.com:5432/dbname?sslmode=disable"

# Environment variable: `CL_DATABASE_ALLOW_SIMPLE_PASSWORDS`
# - AllowSimplePasswords skips the password complexity check normally enforced on URL & BackupURL.
# - Default is false
AllowSimplePasswords = false

#---------------------------#
#         Explorer          #
#---------------------------#

[Explorer]
# AccessKey is the access key for authenticating with the Explorer.
# Environment variable: `CL_EXPLORER_ACCESS_KEY`
# - Example: AccessKey = "access_key"
AccessKey = ""

# Environment variable: `CL_EXPLORER_SECRET`
# Secret is the secret for authenticating with the Explorer.
# - Example: Secret = "secret"
Secret = ""

#---------------------------#
#         Password          #
#---------------------------#
[Password]
# Environment variable: `CL_PASSWORD_KEYSTORE`
# - Keystore is the password for the node's account.
# - Example: Keystore = "keystore_pass"
Keystore = ""

# - VRF is the password for the vrf keys.
# - Example: Environment variable: `CL_PASSWORD_VRF`
# - Example: VRF = "VRF_pass"
#VRF = ""

#---------------------------#
#        Pyroscope          #
#---------------------------#

#[Pyroscope]
# Environment variable: `CL_PYROSCOPE_AUTH_TOKEN`
# - AuthToken is the API key for the Pyroscope server.
# - Example: AuthToken = "pyroscope-token"
#AuthToken = ""

# Mercury credentials are needed if running OCR2 jobs in mercury mode. 0 or
# more Mercury credentials may be specified. URLs must be unique.
#---------------------------#
#         Mercury           #
#---------------------------#
#[Mercury]
#[[Mercury.Credentials]]
# - URL is the URL of the mercury endpoint
# - Example: URL = "http://example.com/reports"
#URL = "http://example.com/reports"

# - Username is used for basic auth with the mercury endpoint
# - Example: Username = "exampleusername"
#Username = "exampleusername"

# - Password is used for basic auth with the mercury endpoint
# - Example: Password = "examplepassword"
#Password = ""
