ExplorerURL = 'wss://'
RootDir = '/.chainlink'

[Feature]
 FeedsManager = true

[Log]
 Level = 'info'
 JSONConsole = false
 UnixTS = false

[Log.File]
 MaxSize = '5120mb'
 MaxAgeDays = 0
 MaxBackups = 1

[WebServer]
 AllowOrigins = '*'

[WebServer.TLS]
 CertPath = '/chainlink/tls/server.crt'
 KeyPath = '/chainlink/tls/server.key'

[JobPipeline]

[JobPipeline.HTTPRequest]
 MaxSize = '700.00kb'

[OCR]
 Enabled = true
 KeyBundleID = ''
 TransmitterAddress = ''

[P2P]
 PeerID = ''

[P2P.V1]
 Enabled = false

[P2P.V2]
 Enabled = true
 AnnounceAddresses = ['']
 DefaultBootstrappers = ['', '', '']
 ListenAddresses = ['']

[[EVM]]
 ChainID = '43114'
 Enabled = true
 LinkContractAddress = '0x5947BB275c521040051D82396192181b413227A3'
 MinContractPayment = '0.00001 link'
 MinIncomingConfirmations = 1

[EVM.GasEstimator]
 Mode = 'BlockHistory'
 PriceDefault = '25 gwei'
 PriceMin = '25 gwei'

[[EVM.Nodes]]
 Name = 'Avalanche_Mainnet_00'
 WSURL = 'wss://'
 HTTPURL = 'https://'
 SendOnly = false
