ExplorerURL = 'wss://'
RootDir = '/chainlink'

[Feature]
 FeedsManager = true

[Log]
 Level = 'info'

[Log.File]
 MaxSize = '5120mb'

[WebServer]
 AllowOrigins = '*'

[WebServer.TLS]
 CertPath = '/chainlink/tls/server.crt'
 KeyPath = '/chainlink/tls/server.key'

[JobPipeline]

[JobPipeline.HTTPRequest]
 DefaultTimeout = '6s'

[OCR]
 Enabled = true
 KeyBundleID = ''
 TransmitterAddress = ''

[P2P]
 PeerID = ''

[P2P.V1]
 Enabled = false

[P2P.V2]
 Enabled = true
 AnnounceAddresses = ['']
 DefaultBootstrappers = ['']
 ListenAddresses = ['']

[[EVM]]
 ChainID = '56'
 Enabled = true
 LinkContractAddress = '0x404460C6A5EdE2D891e8297795264fDe62ADBB75'
 MinContractPayment = '0.1 link'
 MinIncomingConfirmations = 1

[EVM.GasEstimator]
 Mode = 'BlockHistory'
 BumpThreshold = 3

[[EVM.Nodes]]
 Name = 'BinanceSmartChain_Mainnet_00'
 WSURL = 'wss://'
 HTTPURL = 'https://'
 SendOnly = false
