ExplorerURL = 'wss://'
RootDir = '/chainlink'

[Feature]
 FeedsManager = true

[Log]
 Level = 'info'

[Log.File]
 MaxSize = '5120mb'

[WebServer]
AllowOrigins = '*'

[WebServer.TLS]
 CertPath = '/chainlink/tls/server.crt'
 KeyPath = '/chainlink/tls/server.key'

[JobPipeline]

[JobPipeline.HTTPRequest]
 DefaultTimeout = '6s'

[OCR]
 Enabled = true
 KeyBundleID = ''
 TransmitterAddress = ''

[P2P]
PeerID = ''

[P2P.V1]
 Enabled = false

[P2P.V2]
 Enabled = true
 AnnounceAddresses = ['']
 DefaultBootstrappers = ['']
 ListenAddresses = ['']

[[EVM]]
 ChainID = '100'
 Enabled = true
 LinkContractAddress = '0xE2e73A1c69ecF83F464EFCE6A5be353a37cA09b2'
 MinContractPayment = '0.1 link'

[[EVM.Nodes]]
 Name = 'Gnosis_Mainnet_00'
 WSURL = 'wss://'
 HTTPURL = 'https://'
 SendOnly = false
