ExplorerURL = 'wss://'
RootDir = '/chainlink'

[Feature]
 FeedsManager = true

[Log]
 Level = 'info'

[Log.File]
 MaxSize = '5120mb'

[WebServer]
 AllowOrigins = '*'

[WebServer.TLS]
 CertPath = '/chainlink/tls/server.crt'
 KeyPath = '/chainlink/tls/server.key'

[OCR]
 Enabled = true
 ObservationTimeout = '1s'
 KeyBundleID = ''
 TransmitterAddress = ''

[P2P]
 PeerID = ''

[P2P.V1]
 Enabled = false

[P2P.V2]
 Enabled = true
 AnnounceAddresses = ['']
 DefaultBootstrappers = ['']
 ListenAddresses = ['']

[[EVM]]
 ChainID = '1666600000'
 Enabled = true
 MinContractPayment = '0.1 link'

[[EVM.Nodes]]
 Name = 'Harmony_Mainnet_00'
 WSURL = 'wss://'
 HTTPURL = 'https://'
 SendOnly = false
