ExplorerURL = 'wss://'

RootDir = '/chainlink'

[Feature]
 FeedsManager = true

[Log]
 Level = 'info'

[Log.File]
 MaxSize = '5120mb'

[WebServer]
 AllowOrigins = '*'

[WebServer.TLS]
 CertPath = '/chainlink/tls/server.crt'
 KeyPath = '/chainlink/tls/server.key'

[OCR]
 Enabled = true
 KeyBundleID = ''
 TransmitterAddress = ''

[P2P]
 PeerID = ''

[P2P.V1]
 Enabled = false

[P2P.V2]
 Enabled = true
 AnnounceAddresses = ['']
 DefaultBootstrappers = ['']
 ListenAddresses = ['']

[[EVM]]
 ChainID = '137'
 Enabled = true
 LinkContractAddress = '0xb0897686c545045aFc77CF20eC7A532E3120E0F1'
 MinContractPayment = '0.1 link'

[EVM.GasEstimator]
 Mode = 'BlockHistory'
 BumpMin = '16 gwei'
 BumpThreshold = 2

[EVM.GasEstimator.BlockHistory]
 BlockHistorySize = 12
 TransactionPercentile = 75

[[EVM.Nodes]]
 Name = 'Polygon_Mainnet_00'
 WSURL = 'wss://'
 HTTPURL = 'https://'
 SendOnly = false
