RootDir = '/chainlink'

[Feature]
 FeedsManager = true
 LogPoller = true
 UICSAKeys = true

[Database]
 MaxIdleConns = 20
 MaxOpenConns = 40

[TelemetryIngress]
 ServerPubKey = ''
 URL = ''

[Log]
 Level = 'info'

[Log.File]
 MaxSize = '5120mb'

[WebServer]
 AllowOrigins = '*'

[WebServer.TLS]
 CertPath = '/chainlink/tls/server.crt'
 KeyPath = '/chainlink/tls/server.key'

[JobPipeline]

[JobPipeline.HTTPRequest]
 DefaultTimeout = '6s'

[OCR2]
 Enabled = true
 #KeyBundleID = ''

[P2P]
 PeerID = ''
 TraceLogging = true

[P2P.V1]
 Enabled = false

[P2P.V2]
 Enabled = true
 AnnounceAddresses = ['']
 DefaultBootstrappers = ['', '', '', '']
 ListenAddresses = ['']

[[EVM]]
 ChainID = '137'
 Enabled = true
 LinkContractAddress = '0xb0897686c545045aFc77CF20eC7A532E3120E0F1'
 MinContractPayment = '0.1 link'

[[EVM.Nodes]]
 Name = 'Polygon_Mainnet_00'
 WSURL = 'wss://'
 HTTPURL = 'https://'
 SendOnly = false
