#---------------------------#
#         Database          #
#---------------------------#
[Database]
# Environment variable: `CL_DATABASE_URL`
# - URL is the PostgreSQL URI to connect to your database. Chainlink nodes require Postgres versions >= 11. See
# - [Running a Chainlink Node](https://docs.chain.link/docs/running-a-chainlink-node/#set-the-remote-database_url-config) for an example.
# - Example: URL = "postgresql://user:pass@localhost:5432/dbname?sslmode=disable" # Example
URL = ""

# Environment variable: `CL_DATABASE_ALLOW_SIMPLE_PASSWORDS`
# - AllowSimplePasswords skips the password complexity check normally enforced on URL & BackupURL.
# - Default is false
AllowSimplePasswords = false

#---------------------------#
#         Explorer          #
#---------------------------#

[Explorer]
# AccessKey is the access key for authenticating with the Explorer.
# Environment variable: `CL_EXPLORER_ACCESS_KEY`
# - Example: AccessKey = "access_key"
AccessKey = ""

# Environment variable: `CL_EXPLORER_SECRET`
# Secret is the secret for authenticating with the Explorer.
# - Example: Secret = "secret"
Secret = ""

#---------------------------#
#         Password          #
#---------------------------#
[Password]
# Environment variable: `CL_PASSWORD_KEYSTORE`
# - Keystore is the password for the node's account.
# - Example: Keystore = "keystore_pass"
Keystore = ""
